// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iqqbzjoydhmgreavfsai.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlxcWJ6am95ZGhtZ3JlYXZmc2FpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYyODA1ODUsImV4cCI6MjA2MTg1NjU4NX0.X9Idcupz-7vt6NBBGdDKutvvh5Q-CrZpw8C4k06HkIY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);