// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zvdkdisqavthbqmbkfvt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp2ZGtkaXNxYXZ0aGJxbWJrZnZ0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzkzNTQ1NTYsImV4cCI6MjA5NDkzMDU1Nn0.b9jib1-BoWo3GVopCQ_s6EkChhOSl9Q_-_mwnTHC84I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);